service: aws-regression-lambda
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  memorySize: 1024
  timeout: 300
package:
  include:
    - application/**
    - scripts/**
    - system/**
    - node_modules/**
  exclude:
    - tests/**
functions:
  getLinearRegressionModel:
    handler: handler.getLinearRegressionModel
    events:
      - http:
          path: lambda/linear-regression/get-model/{_id}
          method: get
  createLinearRegressionModel:
    handler: handler.createLinearRegressionModel
    events:
      - http:
          path: lambda/linear-regression/create-model
          method: post
  trainLinearRegressionModel:
    handler: handler.trainLinearRegressionModel
    events:
      - http:
          path: lambda/linear-regression/train-model/{_id}
          method: post
  deleteLinearRegressionModel:
    handler: handler.deleteLinearRegressionModel
    events:
      - http:
          path: lambda/linear-regression/delete-model/{_id}
          method: delete